version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: subscription_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: subscription_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:

